# Ports for wireguard
- hosts: wireguard
  become: true
  tasks:
    - community.general.ufw:
        rule: allow
        name: OpenSSH
    
    - name: Allow udp port 51820
      community.general.ufw:
        rule: allow
        port: 51820
        proto: udp

    - community.general.ufw:
        state: enabled


