apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: elasticsearch
  namespace: cattle-logging-system
spec:
  elasticsearch:
    host: elasticsearch-master
    port: 9200
    scheme: http
    logstash_format: true
    suppress_type_name: true
    log_es_400_reason: true
    buffer:
      flush_interval: 5s
      flush_mode: interval
      chunk_limit_size: 8MB
      overflow_action: drop_oldest_chunk   # Prevent OOM on backlog
