apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: mosip-logs
  namespace: cattle-logging-system
spec:
  filters:
    - parser:
        key_name: message
        parse:
          type: json
        replace_invalid_sequence: true
        reserve_data: true
    # Filter all actuator health and actuator prometheus logs as we don't really need them later.
    - grep:
        exclude:
          - key: message
            pattern: /actuator\/health/
    - grep:
        exclude:
          - key: message
            pattern: /actuator\/prometheus/
    # TODO: The below pattern is for unwanted errors from Activemq. We must fix this in Activemq config.
    - grep:
        exclude:
          - key: message
            pattern: /Temporary Store limit is 51200 mb, whilst the temporary data directory:/
  globalOutputRefs:
    - elasticsearch
