global:
  kibanaEnabled: true
data:
  heapSize: 728m
  persistence:
    enabled: true
    size: 64Gi
  resources:
    requests:
      memory: 512Mi
master:
  heapSize: 1024m
  persistence:
    enabled: true
    size: 4Gi
  resources:
    requests:
      memory: 728Mi
kibana:
  persistence:
    enabled: false

sysctlImage:
  repository: bitnami/os-shell
  tag: 12-debian-12-r46
