# Ports to be opened for Rancher as listed here:
# https://rancher.com/docs/rancher/v2.6/en/installation/requirements/ports/#rancher-aws-ec2-security-group
- hosts: cluster
  become: true
  vars:
    vpc_ip: '' #VPC CIDR range of IP e.g 10.20.1.0/24
  tasks:
    - community.general.ufw:
        rule: allow
        name: OpenSSH
    
    - community.general.ufw:
        rule: allow
        port: 80
        proto: tcp
        from: "{{ vpc_ip }}"

    - community.general.ufw:
        rule: allow
        port: 443
        proto: tcp

    - community.general.ufw:
        rule: allow
        port: 2376
        proto: tcp
        from: "{{ vpc_ip }}"

    - community.general.ufw:
        rule: allow
        port: 443
        proto: tcp
        from: "{{ vpc_ip }}"

    - name: Allow port range 10256 for Rancher
      community.general.ufw:
        rule: allow
        port: 10256
        proto: tcp
        from: "{{ vpc_ip }}"

    - name: Allow port range 2379-2380 for Rancher
      community.general.ufw:
        rule: allow
        port: 2379:2380
        proto: tcp
        from: "{{ vpc_ip }}"

    - name: Allow port range 10250-10252 for Rancher
      community.general.ufw:
        rule: allow
        port: 10250:10252   
        proto: tcp
        from: "{{ vpc_ip }}"

    - name: Allow udp port range 4789 for Rancher
      community.general.ufw:
        rule: allow
        port: 4789
        proto: udp
        from: "{{ vpc_ip }}"

    - name: Allow tcp port range 30000-32767 for K8s nodeports
      community.general.ufw:
        rule: allow
        port: 30000:32767   
        proto: tcp
        from: "{{ vpc_ip }}"

    - name: Allow udp port range 30000-32767 for K8s nodeports
      community.general.ufw:
        rule: allow
        port: 30000:32767   
        proto: udp
        from: "{{ vpc_ip }}"

    - name: "Allow udp port 8472"
      community.general.ufw:
        rule: allow
        port: 8472
        proto: udp
        from: "{{ vpc_ip }}"

    - name: "Allow tcp 10250:10252" 
      community.general.ufw:
        rule: allow
        port: 10250:10252   
        proto: tcp
        from: "{{ vpc_ip }}"

    - name: "Allow tcp 6443" 
      community.general.ufw:
        rule: allow
        port: 6443
        proto: tcp
        from: "{{ vpc_ip }}"

    ## Ports for cluster monitoring
    # Node exporter 
    - name: "Allow tcp 9796" 
      community.general.ufw:
        rule: allow
        port: 9796
        proto: tcp
        from: "{{ vpc_ip }}"

    # Nginx ingress controller (not sure if this is required)
    - name: "Allow tcp 10254" 
      community.general.ufw:
        rule: allow
        port: 10254
        proto: tcp
        from: "{{ vpc_ip }}"

    - community.general.ufw:
        state: enabled


