#image:
#Refrain from fixing docker tags. Instead use the appropriate chart version, while helm install
#bitnami/keycloak helm chart version 4.3.0 uses keycloak 14.0.0 version
  #repository: bitnami/keycloak
  #tag: 14.0.0-debian-10-r24
service:
  type: ClusterIP

auth:
  adminUser: admin

ingress:
  enabled: true
  ingressClassName: ""
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname:
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls: []
  secrets: []
  servicePort: http

proxyAddressForwarding: true

replicaCount: 2

# Enable if replicaCount > 1
serviceDiscovery:
  enabled: true

resources:
  limits: {}
  #   cpu: 250m
  #   memory: 1Gi
  requests:
    cpu: 200m
    memory: 1000Mi

rbac:
  create: true
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
