apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rancher
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: rancher
      protocol: HTTP
    hosts:
    - {{ .Values.rancherHost }}
