apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana
spec:
  hosts:
  - "*"
  gateways:
    - kibana
  http:
  - route:
    - destination:
        host: {{ .Values.installName }}
        port:
          number: 5601
    headers:
      request:
        set:
          x-forwarded-proto: https

